#include "platformselectionwindow.h"
#include "ui_platformselectionwindow.h"
#include <QString>
#include <QMessageBox>

PlatformSelectionWindow::PlatformSelectionWindow(Controller* controller, QWidget *parent) :
    QWidget(parent),
    ui(new Ui::platformSelectionWindow)
{
    PlatformSelectionWindow::setController(controller);
    ui->setupUi(this);

    // set window values
    ui->comboBox->setCurrentIndex(this->getController()->getProject()->getPlatformIndex());
    ui->streamKeylineEdit->setText(this->getController()->getProject()->getStreamingKeyQstring());

    // Connect signal buttons
    QObject::connect(ui->okButton, SIGNAL(clicked()),this,SLOT(okPushButtonClicked()));
    QObject::connect(ui->helpButton, SIGNAL(clicked()),this,SLOT(helpButtonClicked()));
    QObject::connect(ui->cancelButton, SIGNAL(clicked()),this,SLOT(cancelPushButtonClicked()));
    QObject::connect(ui->advancedButton, SIGNAL(clicked()),this,SLOT(advancedButtonClicked()));
}

Controller* PlatformSelectionWindow::getController(){
    return controller;
}

void PlatformSelectionWindow::setController(Controller* controller){
    this->controller = controller;
}

PlatformSelectionWindow::~PlatformSelectionWindow()
{
    delete ui;
}

void PlatformSelectionWindow::okPushButtonClicked(){


    if(!ui->streamKeylineEdit->text().isEmpty()){
        this->getController()->setPlatformParameters(ui->comboBox->currentIndex(), ui->streamKeylineEdit->text().toStdString());
        controller->deBlockInterface();
        controller->addFeedback("Project \"" + this->getController()->getProject()->getName() + "\" created");
        this->close();
    }
    else{
         QMessageBox::critical(this,QString::fromStdString("Mising value"),QString::fromStdString("You must specify a streaming key"));
    }
}

void PlatformSelectionWindow::helpButtonClicked(){
    QMessageBox::information(this,QString::fromStdString("Streaming Key"),QString::fromStdString("The streaming key is an unique ID, generated by your broadcasting platform. You can find it on the it. For more information ask your broadcasting platform."));
}

void PlatformSelectionWindow::cancelPushButtonClicked(){
    this->close();
}

void PlatformSelectionWindow::advancedButtonClicked(){
    controller->displayParametersWindow();
}
